#!/bin/bash
sh -c '"/home/mauricio/.config/torbrowser/tor-browser_en-US/Browser/start-tor-browser" --detach || ([ !  -x "/home/mauricio/.config/torbrowser/tor-browser_en-US/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --detach)' dummy %k
